/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormUntukLogin;

import LoginPage.Login;
import Page.PageUser;
import connecction.connect;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import passwordfield.MD5;

/**
 *
 * @author ALYA
 */
public class FormUser extends javax.swing.JFrame {
    String IDuser, namaLengkap, username, password, noTelp;
    int limitLogin;

    /**
     * Creates new form FormPetugas
     */
    public FormUser() {
        initComponents();
        labelKlik.setVisible(false);
        labelLupa.setVisible(false);
        this.setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setBackground(Color.white);
    }
    public void komponen(){
        MD5 hash = new MD5(); 
        IDuser = FieldID.getText().trim();
        namaLengkap = FieldName.getText().trim();
        username = FieldUsername.getText().trim();
        
        password = hash.getMd5(FieldPassword.getText().trim()); 
        System.out.println(password);
        noTelp = FieldTelp.getText().trim();
    
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound_11 = new LoginPage.PanelRound_1();
        panelRound_15 = new LoginPage.PanelRound_1();
        panelRound_16 = new LoginPage.PanelRound_1();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buttonLogin = new button.Button();
        button2 = new button.Button();
        FieldID = new textfield.TextField_1();
        FieldName = new textfield.TextField_1();
        FieldUsername = new textfield.TextField_1();
        FieldPassword = new textfield.PasswordField();
        FieldTelp = new textfield.TextField_1();
        button1 = new button.Button();
        labelLupa = new javax.swing.JLabel();
        labelKlik = new javax.swing.JLabel();
        labelLupa1 = new javax.swing.JLabel();
        labelKlik1 = new javax.swing.JLabel();
        panelRound_17 = new LoginPage.PanelRound_1();
        panelRound_12 = new LoginPage.PanelRound_1();
        panelRound_13 = new LoginPage.PanelRound_1();
        panelRound_14 = new LoginPage.PanelRound_1();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRound_18 = new LoginPage.PanelRound_1();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound_11.setBackground(new java.awt.Color(177, 208, 102));
        panelRound_11.setRoundBottomLeft(100);
        panelRound_11.setRoundBottomRight(100);
        panelRound_11.setRoundTopLeft(100);
        panelRound_11.setRoundTopRight(100);

        panelRound_15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound_15.setRoundBottomLeft(10);
        panelRound_15.setRoundBottomRight(10);
        panelRound_15.setRoundTopLeft(50);
        panelRound_15.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound_15Layout = new javax.swing.GroupLayout(panelRound_15);
        panelRound_15.setLayout(panelRound_15Layout);
        panelRound_15Layout.setHorizontalGroup(
            panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        panelRound_15Layout.setVerticalGroup(
            panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        panelRound_16.setBackground(new java.awt.Color(255, 255, 255));
        panelRound_16.setRoundBottomLeft(50);
        panelRound_16.setRoundBottomRight(50);
        panelRound_16.setRoundTopLeft(10);
        panelRound_16.setRoundTopRight(10);

        javax.swing.GroupLayout panelRound_16Layout = new javax.swing.GroupLayout(panelRound_16);
        panelRound_16.setLayout(panelRound_16Layout);
        panelRound_16Layout.setHorizontalGroup(
            panelRound_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        panelRound_16Layout.setVerticalGroup(
            panelRound_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAMA");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USERNAME");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("KATA SANDI");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NO");

        buttonLogin.setForeground(new java.awt.Color(177, 208, 102));
        buttonLogin.setText("LOGIN");
        buttonLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        buttonLogin.setShadowColor(new java.awt.Color(177, 208, 102));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        button2.setForeground(new java.awt.Color(177, 208, 102));
        button2.setText("HAPUS");
        button2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        button2.setShadowColor(new java.awt.Color(177, 208, 102));

        FieldID.setLabelText("Masukkan ID");

        FieldName.setLabelText("Masukkan Nama");
        FieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldNameKeyPressed(evt);
            }
        });

        FieldUsername.setLabelText("Masukkan Username");
        FieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldUsernameKeyPressed(evt);
            }
        });

        FieldPassword.setLabelText("Masukkan Kata Sandi");
        FieldPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FieldPasswordMouseClicked(evt);
            }
        });
        FieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldPasswordKeyPressed(evt);
            }
        });

        FieldTelp.setLabelText("Masukkan No Telp");

        button1.setForeground(new java.awt.Color(177, 208, 102));
        button1.setText("KELUAR");
        button1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        labelLupa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelLupa.setForeground(new java.awt.Color(255, 255, 255));
        labelLupa.setText("Lupa Kata Sandi?");

        labelKlik.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelKlik.setForeground(new java.awt.Color(255, 255, 255));
        labelKlik.setText("<html> <u> Klik Disini </u>  </html>");
        labelKlik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKlikMouseClicked(evt);
            }
        });

        labelLupa1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelLupa1.setForeground(new java.awt.Color(255, 255, 255));
        labelLupa1.setText("Belum Punya Akun?");

        labelKlik1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelKlik1.setForeground(new java.awt.Color(255, 255, 255));
        labelKlik1.setText("<html> <u> Klik Disini </u>  </html>");
        labelKlik1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKlik1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound_11Layout = new javax.swing.GroupLayout(panelRound_11);
        panelRound_11.setLayout(panelRound_11Layout);
        panelRound_11Layout.setHorizontalGroup(
            panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_11Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_11Layout.createSequentialGroup()
                        .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelRound_11Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7)))
                                .addGroup(panelRound_11Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(panelRound_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelRound_11Layout.createSequentialGroup()
                                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(51, 51, 51)
                                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FieldTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound_11Layout.createSequentialGroup()
                                        .addComponent(labelLupa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelKlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)))
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_11Layout.createSequentialGroup()
                        .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))
                    .addGroup(panelRound_11Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(panelRound_16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(panelRound_11Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(labelLupa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelKlik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound_11Layout.setVerticalGroup(
            panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_11Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(panelRound_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound_11Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel4))
                    .addGroup(panelRound_11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLupa)
                    .addComponent(labelKlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLupa1)
                    .addComponent(labelKlik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelRound_16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(panelRound_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, -1, 970));

        panelRound_17.setBackground(new java.awt.Color(177, 208, 102));
        panelRound_17.setRoundBottomLeft(30);
        panelRound_17.setRoundBottomRight(30);
        panelRound_17.setRoundTopLeft(30);
        panelRound_17.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_17Layout = new javax.swing.GroupLayout(panelRound_17);
        panelRound_17.setLayout(panelRound_17Layout);
        panelRound_17Layout.setHorizontalGroup(
            panelRound_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelRound_17Layout.setVerticalGroup(
            panelRound_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, -90, 40, -1));

        panelRound_12.setBackground(new java.awt.Color(177, 208, 102));
        panelRound_12.setRoundBottomLeft(30);
        panelRound_12.setRoundBottomRight(30);
        panelRound_12.setRoundTopLeft(30);
        panelRound_12.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_12Layout = new javax.swing.GroupLayout(panelRound_12);
        panelRound_12.setLayout(panelRound_12Layout);
        panelRound_12Layout.setHorizontalGroup(
            panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        panelRound_12Layout.setVerticalGroup(
            panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 770, 270, 30));

        panelRound_13.setBackground(new java.awt.Color(177, 208, 102));
        panelRound_13.setRoundBottomLeft(30);
        panelRound_13.setRoundBottomRight(30);
        panelRound_13.setRoundTopLeft(30);
        panelRound_13.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_13Layout = new javax.swing.GroupLayout(panelRound_13);
        panelRound_13.setLayout(panelRound_13Layout);
        panelRound_13Layout.setHorizontalGroup(
            panelRound_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelRound_13Layout.setVerticalGroup(
            panelRound_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 750, 40, 370));

        panelRound_14.setBackground(new java.awt.Color(177, 208, 102));
        panelRound_14.setRoundBottomLeft(30);
        panelRound_14.setRoundBottomRight(30);
        panelRound_14.setRoundTopLeft(30);
        panelRound_14.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_14Layout = new javax.swing.GroupLayout(panelRound_14);
        panelRound_14.setLayout(panelRound_14Layout);
        panelRound_14Layout.setHorizontalGroup(
            panelRound_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelRound_14Layout.setVerticalGroup(
            panelRound_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 40, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormUntukLogin/man.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(177, 208, 102));
        jLabel2.setText("FORM LOGIN MASYARAKAT.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 730, -1, -1));

        panelRound_18.setBackground(new java.awt.Color(177, 208, 102));
        panelRound_18.setRoundBottomLeft(30);
        panelRound_18.setRoundBottomRight(30);
        panelRound_18.setRoundTopLeft(30);
        panelRound_18.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_18Layout = new javax.swing.GroupLayout(panelRound_18);
        panelRound_18.setLayout(panelRound_18Layout);
        panelRound_18Layout.setHorizontalGroup(
            panelRound_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelRound_18Layout.setVerticalGroup(
            panelRound_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, -180, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        komponen();
//        
        if (IDuser.equals("")){
            JOptionPane.showMessageDialog(null, "Anda Salah Memasukkan ID!", "Wrong ID", JOptionPane.ERROR_MESSAGE);
        }else if(namaLengkap.equals("")){
            JOptionPane.showMessageDialog(null, "Nama Anda Tidak Dapat Ditemukan!", "NOT FOUND", JOptionPane.ERROR_MESSAGE);
        }else if(noTelp.equals("")){
            JOptionPane.showMessageDialog(null, "Nomor Telepon Tidak Dapat Ditemukan!", "NOT FOUND", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                Connection con = connect.connectDB();
                String sql = "SELECT * FROM tb_masyarakat where id ='"+IDuser+
                        "'and nama ='"+namaLengkap+
                        "'and username ='"+username+"'and password='"+password+"'and telp='"+noTelp+"'";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet set = pst.executeQuery(sql);
                if(set.next()){
                    
                        JOptionPane.showMessageDialog(null, "Login Sukses! Anda Masuk Sebagai "+set.getNString("nama"), "Sukses", JOptionPane.INFORMATION_MESSAGE);
                            PageUser a = new PageUser();
                            a.setVisible(true);
                            this.setVisible(false);
                        
                }else{
                    JOptionPane.showMessageDialog(null, "Login Gagal!", "Error", JOptionPane.ERROR_MESSAGE);
                    limitLogin+=1;
                    if(limitLogin==3){
                        labelKlik.setVisible(true);
                        labelLupa.setVisible(true);
                    }
                }
            }catch (Exception e){
            }   
            }
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        new Login().setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void FieldPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldPasswordMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_FieldPasswordMouseClicked

    private void labelKlikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKlikMouseClicked
        new NewPasswordMasyarakat().setVisible(true);
        
    }//GEN-LAST:event_labelKlikMouseClicked

    private void FieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNameKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            FieldUsername.requestFocus();
        }
    }//GEN-LAST:event_FieldNameKeyPressed

    private void FieldUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldUsernameKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            FieldPassword.requestFocus();
        }
    }//GEN-LAST:event_FieldUsernameKeyPressed

    private void FieldPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldPasswordKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            FieldTelp.requestFocus();
        }
    }//GEN-LAST:event_FieldPasswordKeyPressed

    private void labelKlik1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKlik1MouseClicked
        new MembuatAkunMasyarakat().setVisible(true);
    }//GEN-LAST:event_labelKlik1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private textfield.TextField_1 FieldID;
    private textfield.TextField_1 FieldName;
    private textfield.PasswordField FieldPassword;
    private textfield.TextField_1 FieldTelp;
    private textfield.TextField_1 FieldUsername;
    private button.Button button1;
    private button.Button button2;
    private button.Button buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelKlik;
    private javax.swing.JLabel labelKlik1;
    private javax.swing.JLabel labelLupa;
    private javax.swing.JLabel labelLupa1;
    private LoginPage.PanelRound_1 panelRound_11;
    private LoginPage.PanelRound_1 panelRound_12;
    private LoginPage.PanelRound_1 panelRound_13;
    private LoginPage.PanelRound_1 panelRound_14;
    private LoginPage.PanelRound_1 panelRound_15;
    private LoginPage.PanelRound_1 panelRound_16;
    private LoginPage.PanelRound_1 panelRound_17;
    private LoginPage.PanelRound_1 panelRound_18;
    // End of variables declaration//GEN-END:variables
}
