/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormUntukLogin;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import LoginPage.Login;
import Page.PageAP;
import Page.PagePetugas;
import connecction.connect;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import passwordfield.MD5;



/**
 *
 * @author ALYA
 */
public class formPetugas extends javax.swing.JFrame {
    String hakAkses, IDpetugas, namaLengkap, username, password;
    PreparedStatement pst; 
    ResultSet set; 
    
    int limitlogin;
    
    
    
     public formPetugas() {
        initComponents();
        getContentPane().setBackground(Color.white);
        fieldHakAkses.setEditable(false);
        labelLupa.setVisible(false);
        labelkliklupa.setVisible(false);
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
   
    public void komponen(){
        MD5 hash = new MD5();
        hakAkses = fieldHakAkses.getText(); 
        IDpetugas = FieldIDPetugas.getText().trim(); 
        namaLengkap = fieldNamaPetugas.getText().trim();
        username = FieldUsernamePetugas.getText().trim();
        password = fieldPasswordPetugas.getText().trim(); 
        System.out.println(password);
        
      
     
        
       
        
       
    }
    
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound_11 = new LoginPage.PanelRound_1();
        panelRound_15 = new LoginPage.PanelRound_1();
        panelRound_16 = new LoginPage.PanelRound_1();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ButtonLogin = new button.Button();
        button2 = new button.Button();
        FieldIDPetugas = new textfield.TextField_1();
        fieldNamaPetugas = new textfield.TextField_1();
        FieldUsernamePetugas = new textfield.TextField_1();
        fieldPasswordPetugas = new textfield.PasswordField();
        button1 = new button.Button();
        fieldHakAkses = new textfield.TextField_1();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelLupa = new javax.swing.JLabel();
        labelkliklupa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelRound_12 = new LoginPage.PanelRound_1();
        jLabel2 = new javax.swing.JLabel();
        panelRound_13 = new LoginPage.PanelRound_1();
        panelRound_14 = new LoginPage.PanelRound_1();
        panelRound_17 = new LoginPage.PanelRound_1();
        panelRound_18 = new LoginPage.PanelRound_1();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound_11.setBackground(new java.awt.Color(255, 204, 51));
        panelRound_11.setRoundBottomLeft(100);
        panelRound_11.setRoundBottomRight(100);
        panelRound_11.setRoundTopLeft(100);
        panelRound_11.setRoundTopRight(100);
        panelRound_11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound_15.setBackground(new java.awt.Color(255, 102, 102));
        panelRound_15.setRoundBottomLeft(50);
        panelRound_15.setRoundBottomRight(50);
        panelRound_15.setRoundTopLeft(10);
        panelRound_15.setRoundTopRight(10);

        javax.swing.GroupLayout panelRound_15Layout = new javax.swing.GroupLayout(panelRound_15);
        panelRound_15.setLayout(panelRound_15Layout);
        panelRound_15Layout.setHorizontalGroup(
            panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        panelRound_15Layout.setVerticalGroup(
            panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelRound_11.add(panelRound_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 800, 780, -1));

        panelRound_16.setBackground(new java.awt.Color(255, 102, 102));
        panelRound_16.setRoundBottomLeft(10);
        panelRound_16.setRoundBottomRight(10);
        panelRound_16.setRoundTopLeft(50);
        panelRound_16.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound_16Layout = new javax.swing.GroupLayout(panelRound_16);
        panelRound_16.setLayout(panelRound_16Layout);
        panelRound_16Layout.setHorizontalGroup(
            panelRound_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        panelRound_16Layout.setVerticalGroup(
            panelRound_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        panelRound_11.add(panelRound_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("ID");
        panelRound_11.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("NAMA");
        panelRound_11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("USERNAME");
        panelRound_11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("PASSWORD");
        panelRound_11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("SEBAGAI");
        panelRound_11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        ButtonLogin.setBackground(new java.awt.Color(255, 102, 102));
        ButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormUntukLogin/sign-in-alt.png"))); // NOI18N
        ButtonLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonLogin.setShadowColor(new java.awt.Color(204, 51, 255));
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });
        panelRound_11.add(ButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 730, 89, -1));

        button2.setBackground(new java.awt.Color(255, 102, 102));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/trash-bin.png"))); // NOI18N
        button2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        button2.setShadowColor(new java.awt.Color(204, 51, 255));
        panelRound_11.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 730, 95, -1));

        FieldIDPetugas.setLabelText("isi id anda");
        FieldIDPetugas.setLineColor(new java.awt.Color(204, 153, 255));
        panelRound_11.add(FieldIDPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 551, -1));

        fieldNamaPetugas.setLabelText("isi nama anda");
        fieldNamaPetugas.setLineColor(new java.awt.Color(204, 153, 255));
        fieldNamaPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaPetugasActionPerformed(evt);
            }
        });
        panelRound_11.add(fieldNamaPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 551, -1));

        FieldUsernamePetugas.setLabelText("isi username anda");
        FieldUsernamePetugas.setLineColor(new java.awt.Color(204, 153, 255));
        panelRound_11.add(FieldUsernamePetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 551, -1));

        fieldPasswordPetugas.setLabelText("isi password anda");
        fieldPasswordPetugas.setLineColor(new java.awt.Color(204, 153, 255));
        fieldPasswordPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasswordPetugasActionPerformed(evt);
            }
        });
        panelRound_11.add(fieldPasswordPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 551, -1));

        button1.setBackground(new java.awt.Color(255, 102, 102));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/logout.png"))); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelRound_11.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 730, 99, 58));

        fieldHakAkses.setText("Petugas");
        fieldHakAkses.setLabelText("Anda Sebagai");
        fieldHakAkses.setLineColor(new java.awt.Color(204, 153, 255));
        panelRound_11.add(fieldHakAkses, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 551, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Belum punya akun?");
        panelRound_11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 680, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html><u>Klik disini<u/></html>");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panelRound_11.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 680, -1, -1));

        labelLupa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        labelLupa.setForeground(new java.awt.Color(255, 255, 255));
        labelLupa.setText("Lupa Password?");
        panelRound_11.add(labelLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, -1, -1));

        labelkliklupa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        labelkliklupa.setForeground(new java.awt.Color(255, 255, 255));
        labelkliklupa.setText("<html><u>Klik disini<u/></html>");
        labelkliklupa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelkliklupaMouseClicked(evt);
            }
        });
        panelRound_11.add(labelkliklupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, -1, -1));

        getContentPane().add(panelRound_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 970, 900));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormUntukLogin/man (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        panelRound_12.setBackground(new java.awt.Color(255, 102, 102));
        panelRound_12.setRoundBottomLeft(30);
        panelRound_12.setRoundBottomRight(30);
        panelRound_12.setRoundTopLeft(30);
        panelRound_12.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_12Layout = new javax.swing.GroupLayout(panelRound_12);
        panelRound_12.setLayout(panelRound_12Layout);
        panelRound_12Layout.setHorizontalGroup(
            panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        panelRound_12Layout.setVerticalGroup(
            panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 770, 270, 30));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("FORM LOGIN PETUGAS.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 730, -1, -1));

        panelRound_13.setBackground(new java.awt.Color(255, 102, 102));
        panelRound_13.setRoundBottomLeft(30);
        panelRound_13.setRoundBottomRight(30);
        panelRound_13.setRoundTopLeft(30);
        panelRound_13.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_13Layout = new javax.swing.GroupLayout(panelRound_13);
        panelRound_13.setLayout(panelRound_13Layout);
        panelRound_13Layout.setHorizontalGroup(
            panelRound_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelRound_13Layout.setVerticalGroup(
            panelRound_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 750, 40, 370));

        panelRound_14.setBackground(new java.awt.Color(255, 102, 102));
        panelRound_14.setRoundBottomLeft(30);
        panelRound_14.setRoundBottomRight(30);
        panelRound_14.setRoundTopLeft(30);
        panelRound_14.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_14Layout = new javax.swing.GroupLayout(panelRound_14);
        panelRound_14.setLayout(panelRound_14Layout);
        panelRound_14Layout.setHorizontalGroup(
            panelRound_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelRound_14Layout.setVerticalGroup(
            panelRound_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 40, 370));

        panelRound_17.setBackground(new java.awt.Color(255, 102, 102));
        panelRound_17.setRoundBottomLeft(30);
        panelRound_17.setRoundBottomRight(30);
        panelRound_17.setRoundTopLeft(30);
        panelRound_17.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_17Layout = new javax.swing.GroupLayout(panelRound_17);
        panelRound_17.setLayout(panelRound_17Layout);
        panelRound_17Layout.setHorizontalGroup(
            panelRound_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelRound_17Layout.setVerticalGroup(
            panelRound_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, -90, 40, -1));

        panelRound_18.setBackground(new java.awt.Color(255, 102, 102));
        panelRound_18.setRoundBottomLeft(30);
        panelRound_18.setRoundBottomRight(30);
        panelRound_18.setRoundTopLeft(30);
        panelRound_18.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_18Layout = new javax.swing.GroupLayout(panelRound_18);
        panelRound_18.setLayout(panelRound_18Layout);
        panelRound_18Layout.setHorizontalGroup(
            panelRound_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelRound_18Layout.setVerticalGroup(
            panelRound_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, -180, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      
    }//GEN-LAST:event_formWindowOpened

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        // TODO add your handling code here:
        komponen();
        
     
        if (IDpetugas.isEmpty()){
            JOptionPane.showMessageDialog(null, "ID tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(namaLengkap.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(username.isEmpty()){
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        
    else if(password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            try{
                String sql = "select * from tb_petugas join tb_level using(id_level) where level=? and id_petugas=? and nama_petugas=? and username=? and password=?"; 
            
                this.pst = connect.connectDB().prepareStatement(sql); 
                this.pst.setString(1, hakAkses); 
                this.pst.setString(2, IDpetugas); 
                this.pst.setString(3, namaLengkap); 
                this.pst.setString(4, username); 
                this.pst.setString(5, password); 
                this.set = pst.executeQuery(); 
             
              
               
                
               
                if(set.next()){
                         
                        JOptionPane.showMessageDialog(null, "Login Sukses! Anda Login Sebagai "+hakAkses, "Sukses", JOptionPane.INFORMATION_MESSAGE);
                      new PagePetugas().setVisible(true);
                      
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Login Gagal!", "Error", JOptionPane.ERROR_MESSAGE);
                    limitlogin+=1;
                    if(limitlogin==3){
                        labelkliklupa.setVisible(true);
                        labelLupa.setVisible(true);
                    }
                }
            }catch (Exception e){
            }   
            }
    }//GEN-LAST:event_ButtonLoginActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        new Login().setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void fieldNamaPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaPetugasActionPerformed

    private void fieldPasswordPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasswordPetugasActionPerformed

    private void labelkliklupaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkliklupaMouseClicked
        new NewPassword().setVisible(true);
    }//GEN-LAST:event_labelkliklupaMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new MembuatAkunPetugas().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPetugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button ButtonLogin;
    private textfield.TextField_1 FieldIDPetugas;
    private textfield.TextField_1 FieldUsernamePetugas;
    private button.Button button1;
    private button.Button button2;
    private textfield.TextField_1 fieldHakAkses;
    private textfield.TextField_1 fieldNamaPetugas;
    private textfield.PasswordField fieldPasswordPetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelLupa;
    private javax.swing.JLabel labelkliklupa;
    private LoginPage.PanelRound_1 panelRound_11;
    private LoginPage.PanelRound_1 panelRound_12;
    private LoginPage.PanelRound_1 panelRound_13;
    private LoginPage.PanelRound_1 panelRound_14;
    private LoginPage.PanelRound_1 panelRound_15;
    private LoginPage.PanelRound_1 panelRound_16;
    private LoginPage.PanelRound_1 panelRound_17;
    private LoginPage.PanelRound_1 panelRound_18;
    // End of variables declaration//GEN-END:variables

   
  
   
    
}
