/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormUntukLogin;

import LoginPage.Login;
import Page.PageAP;
import Page.PagePetugas;
import connecction.connect;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import passwordfield.MD5;



/**
 *
 * @author ALYA
 */
public class FormAdmin extends javax.swing.JFrame {
    String hakAkses, IDpetugas, namaLengkap, username, password;
    PreparedStatement pst; 
    ResultSet set; 
    
    

    /**
     * Creates new form FormAdmin
     */
    public FormAdmin() {
        initComponents();
        FieldHakAkses.setEditable(false);
        this.setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setBackground(Color.white);
        
    }
    public void komponen(){
        MD5 hash = new MD5();
        hakAkses = FieldHakAkses.getText();
        IDpetugas = FieldIdAdmin.getText().trim();
        namaLengkap = FieldNamaAdmin.getText().trim();
        username = FieldUsernameAdmin.getText().trim();
        password = hash.getMd5(FieldPasswordAdmin.getText().trim());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound_12 = new LoginPage.PanelRound_1();
        panelRound_15 = new LoginPage.PanelRound_1();
        panelRound_16 = new LoginPage.PanelRound_1();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ButtonLogin = new button.Button();
        button2 = new button.Button();
        FieldHakAkses = new textfield.TextField_1();
        FieldNamaAdmin = new textfield.TextField_1();
        FieldUsernameAdmin = new textfield.TextField_1();
        FieldPasswordAdmin = new textfield.PasswordField();
        button1 = new button.Button();
        FieldIdAdmin = new textfield.TextField_1();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelRound_11 = new LoginPage.PanelRound_1();
        jLabel2 = new javax.swing.JLabel();
        panelRound_13 = new LoginPage.PanelRound_1();
        panelRound_14 = new LoginPage.PanelRound_1();
        panelRound_17 = new LoginPage.PanelRound_1();
        panelRound_18 = new LoginPage.PanelRound_1();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound_12.setBackground(new java.awt.Color(255, 204, 51));
        panelRound_12.setRoundBottomLeft(100);
        panelRound_12.setRoundBottomRight(100);
        panelRound_12.setRoundTopLeft(100);
        panelRound_12.setRoundTopRight(100);

        panelRound_15.setBackground(new java.awt.Color(204, 153, 255));
        panelRound_15.setRoundBottomLeft(50);
        panelRound_15.setRoundBottomRight(50);
        panelRound_15.setRoundTopLeft(10);
        panelRound_15.setRoundTopRight(10);

        javax.swing.GroupLayout panelRound_15Layout = new javax.swing.GroupLayout(panelRound_15);
        panelRound_15.setLayout(panelRound_15Layout);
        panelRound_15Layout.setHorizontalGroup(
            panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        panelRound_15Layout.setVerticalGroup(
            panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelRound_16.setBackground(new java.awt.Color(204, 153, 255));
        panelRound_16.setRoundBottomLeft(10);
        panelRound_16.setRoundBottomRight(10);
        panelRound_16.setRoundTopLeft(50);
        panelRound_16.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound_16Layout = new javax.swing.GroupLayout(panelRound_16);
        panelRound_16.setLayout(panelRound_16Layout);
        panelRound_16Layout.setHorizontalGroup(
            panelRound_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        panelRound_16Layout.setVerticalGroup(
            panelRound_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NAMA");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("USERNAME");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PASSWORD");

        ButtonLogin.setBackground(new java.awt.Color(204, 153, 255));
        ButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormUntukLogin/sign-in-alt.png"))); // NOI18N
        ButtonLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonLogin.setShadowColor(new java.awt.Color(204, 51, 255));
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(204, 153, 255));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/trash-bin.png"))); // NOI18N
        button2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        button2.setShadowColor(new java.awt.Color(204, 51, 255));

        FieldHakAkses.setText("Administrator");
        FieldHakAkses.setLabelText("anda sebagai");
        FieldHakAkses.setLineColor(new java.awt.Color(204, 153, 255));

        FieldNamaAdmin.setLabelText("isi nama anda");
        FieldNamaAdmin.setLineColor(new java.awt.Color(204, 153, 255));
        FieldNamaAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldNamaAdminKeyPressed(evt);
            }
        });

        FieldUsernameAdmin.setLabelText("isi username anda");
        FieldUsernameAdmin.setLineColor(new java.awt.Color(204, 153, 255));
        FieldUsernameAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldUsernameAdminKeyPressed(evt);
            }
        });

        FieldPasswordAdmin.setLabelText("isi password anda");
        FieldPasswordAdmin.setLineColor(new java.awt.Color(204, 153, 255));

        button1.setBackground(new java.awt.Color(204, 153, 255));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/logout.png"))); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        FieldIdAdmin.setLabelText("isi id anda");
        FieldIdAdmin.setLineColor(new java.awt.Color(204, 153, 255));
        FieldIdAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldIdAdminActionPerformed(evt);
            }
        });
        FieldIdAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldIdAdminKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SEBAGAI");

        javax.swing.GroupLayout panelRound_12Layout = new javax.swing.GroupLayout(panelRound_12);
        panelRound_12.setLayout(panelRound_12Layout);
        panelRound_12Layout.setHorizontalGroup(
            panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_12Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_12Layout.createSequentialGroup()
                        .addComponent(ButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelRound_16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRound_12Layout.createSequentialGroup()
                                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(552, 552, 552)))
                        .addComponent(jLabel10)
                        .addGroup(panelRound_12Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelRound_12Layout.createSequentialGroup()
                                    .addComponent(panelRound_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelRound_12Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(FieldNamaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FieldIdAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FieldUsernameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FieldHakAkses, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FieldPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(17, 17, 17))))))
                .addGap(150, 150, 150))
        );
        panelRound_12Layout.setVerticalGroup(
            panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_12Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(panelRound_16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldHakAkses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound_12Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel5))
                    .addGroup(panelRound_12Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(FieldIdAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(FieldNamaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound_12Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel7))
                    .addGroup(panelRound_12Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(FieldUsernameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(FieldPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(panelRound_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(panelRound_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 1000, 920));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormUntukLogin/woman.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        panelRound_11.setBackground(new java.awt.Color(255, 204, 51));
        panelRound_11.setRoundBottomLeft(30);
        panelRound_11.setRoundBottomRight(30);
        panelRound_11.setRoundTopLeft(30);
        panelRound_11.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_11Layout = new javax.swing.GroupLayout(panelRound_11);
        panelRound_11.setLayout(panelRound_11Layout);
        panelRound_11Layout.setHorizontalGroup(
            panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        panelRound_11Layout.setVerticalGroup(
            panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 770, 270, 30));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("FORM LOGIN ADMIN.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 730, -1, -1));

        panelRound_13.setBackground(new java.awt.Color(255, 204, 51));
        panelRound_13.setRoundBottomLeft(30);
        panelRound_13.setRoundBottomRight(30);
        panelRound_13.setRoundTopLeft(30);
        panelRound_13.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_13Layout = new javax.swing.GroupLayout(panelRound_13);
        panelRound_13.setLayout(panelRound_13Layout);
        panelRound_13Layout.setHorizontalGroup(
            panelRound_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelRound_13Layout.setVerticalGroup(
            panelRound_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 750, 40, 370));

        panelRound_14.setBackground(new java.awt.Color(255, 204, 51));
        panelRound_14.setRoundBottomLeft(30);
        panelRound_14.setRoundBottomRight(30);
        panelRound_14.setRoundTopLeft(30);
        panelRound_14.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_14Layout = new javax.swing.GroupLayout(panelRound_14);
        panelRound_14.setLayout(panelRound_14Layout);
        panelRound_14Layout.setHorizontalGroup(
            panelRound_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelRound_14Layout.setVerticalGroup(
            panelRound_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 40, 370));

        panelRound_17.setBackground(new java.awt.Color(255, 204, 51));
        panelRound_17.setRoundBottomLeft(30);
        panelRound_17.setRoundBottomRight(30);
        panelRound_17.setRoundTopLeft(30);
        panelRound_17.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_17Layout = new javax.swing.GroupLayout(panelRound_17);
        panelRound_17.setLayout(panelRound_17Layout);
        panelRound_17Layout.setHorizontalGroup(
            panelRound_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelRound_17Layout.setVerticalGroup(
            panelRound_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, -90, 40, -1));

        panelRound_18.setBackground(new java.awt.Color(255, 204, 51));
        panelRound_18.setRoundBottomLeft(30);
        panelRound_18.setRoundBottomRight(30);
        panelRound_18.setRoundTopLeft(30);
        panelRound_18.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound_18Layout = new javax.swing.GroupLayout(panelRound_18);
        panelRound_18.setLayout(panelRound_18Layout);
        panelRound_18Layout.setHorizontalGroup(
            panelRound_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelRound_18Layout.setVerticalGroup(
            panelRound_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelRound_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, -180, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowOpened

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        new Login().setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        // TODO add your handling code here:
        komponen();

        if (IDpetugas.isEmpty()){
            JOptionPane.showMessageDialog(null, "ID tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(namaLengkap.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(username.isEmpty()){
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);

        }

        else if(password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);

        }
        else{
            try{
                String sql = "select * from tb_petugas join tb_level using(id_level) where level=? and id_petugas=? and nama_petugas=? and username=? and password=?";

                this.pst = connect.connectDB().prepareStatement(sql);
                this.pst.setString(1, hakAkses);
                this.pst.setString(2, IDpetugas);
                this.pst.setString(3, namaLengkap);
                this.pst.setString(4, username);
                this.pst.setString(5, password);
                this.set = pst.executeQuery();
             

                if(set.next()){
                    JOptionPane.showMessageDialog(null, "Login Sukses! Anda Login Sebagai "+hakAkses, "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    new PageAP().setVisible(true);
                  

                }
            }catch (Exception e){
            }
        }
    }//GEN-LAST:event_ButtonLoginActionPerformed

    private void FieldIdAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldIdAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldIdAdminActionPerformed

    private void FieldIdAdminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldIdAdminKeyPressed
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            FieldNamaAdmin.requestFocus();
        }
    }//GEN-LAST:event_FieldIdAdminKeyPressed

    private void FieldNamaAdminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNamaAdminKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            FieldUsernameAdmin.requestFocus();
        }
                   
    }//GEN-LAST:event_FieldNamaAdminKeyPressed

    private void FieldUsernameAdminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldUsernameAdminKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            FieldPasswordAdmin.requestFocus();
        }             
    }//GEN-LAST:event_FieldUsernameAdminKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button ButtonLogin;
    private textfield.TextField_1 FieldHakAkses;
    private textfield.TextField_1 FieldIdAdmin;
    private textfield.TextField_1 FieldNamaAdmin;
    private textfield.PasswordField FieldPasswordAdmin;
    private textfield.TextField_1 FieldUsernameAdmin;
    private button.Button button1;
    private button.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private LoginPage.PanelRound_1 panelRound_11;
    private LoginPage.PanelRound_1 panelRound_12;
    private LoginPage.PanelRound_1 panelRound_13;
    private LoginPage.PanelRound_1 panelRound_14;
    private LoginPage.PanelRound_1 panelRound_15;
    private LoginPage.PanelRound_1 panelRound_16;
    private LoginPage.PanelRound_1 panelRound_17;
    private LoginPage.PanelRound_1 panelRound_18;
    // End of variables declaration//GEN-END:variables

}