/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormUntukLogin;

import connecction.connect;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import passwordfield.MD5;

/**
 *
 * @author ALYA
 */
public class MembuatAkunMasyarakat extends javax.swing.JFrame {
    String InputidMasyarakat, InputNamaMasyarakat, InputUsernameMasyarakat, InputPsswordMasyarakat, InputNoMasyarakat;
    
    PreparedStatement pst;
    ResultSet rs;
    

    /**
     * Creates new form MembuatAkunMasyarakat
     */
    public MembuatAkunMasyarakat() {
        
        initComponents();
        AutoNumberID();
        FieldPasswordMasyarakat.setVisible(false);
        FieldNoTelp.setVisible(false);
        getContentPane().setBackground(Color.WHITE);
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    public void komponen(){
        MD5 hash = new MD5(); 
        
        InputidMasyarakat = FieldIDMasyarakat.getText().trim();
        InputNamaMasyarakat = FieldNamaMasyarakat.getText().trim();
        InputUsernameMasyarakat = FieldUsernameMasyarakat.getText().trim();
        InputPsswordMasyarakat = hash.getMd5(FieldPasswordMasyarakat.getText().trim()); 
        InputNoMasyarakat = FieldNoTelp.getText().trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelRound_12 = new LoginPage.PanelRound_1();
        panelRound_11 = new LoginPage.PanelRound_1();
        jLabel1 = new javax.swing.JLabel();
        FieldIDMasyarakat = new textfield.TextField();
        FieldNamaMasyarakat = new textfield.TextField();
        FieldUsernameMasyarakat = new textfield.TextField();
        FieldPasswordMasyarakat = new textfield.TextField();
        FieldNoTelp = new textfield.TextField();
        ButtonSimpanAkun = new button.Button();
        labelError = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormUntukLogin/user (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 360));

        panelRound_12.setBackground(new java.awt.Color(255, 60, 124));

        panelRound_11.setBackground(new java.awt.Color(255, 255, 255));
        panelRound_11.setRoundBottomLeft(50);
        panelRound_11.setRoundBottomRight(50);
        panelRound_11.setRoundTopLeft(50);
        panelRound_11.setRoundTopRight(50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormUntukLogin/profile-user.png"))); // NOI18N

        FieldIDMasyarakat.setLabelText("ID");
        FieldIDMasyarakat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldIDMasyarakatKeyReleased(evt);
            }
        });

        FieldNamaMasyarakat.setLabelText("Nama Anda");
        FieldNamaMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNamaMasyarakatActionPerformed(evt);
            }
        });
        FieldNamaMasyarakat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldNamaMasyarakatKeyPressed(evt);
            }
        });

        FieldUsernameMasyarakat.setLabelText("Username");
        FieldUsernameMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldUsernameMasyarakatActionPerformed(evt);
            }
        });
        FieldUsernameMasyarakat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldUsernameMasyarakatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldUsernameMasyarakatKeyReleased(evt);
            }
        });

        FieldPasswordMasyarakat.setLabelText("Password");
        FieldPasswordMasyarakat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldPasswordMasyarakatKeyPressed(evt);
            }
        });

        FieldNoTelp.setLabelText("Nomor Telepon");
        FieldNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNoTelpActionPerformed(evt);
            }
        });
        FieldNoTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldNoTelpKeyPressed(evt);
            }
        });

        ButtonSimpanAkun.setBackground(new java.awt.Color(0, 51, 255));
        ButtonSimpanAkun.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSimpanAkun.setText("Buat Akun");
        ButtonSimpanAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanAkunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound_11Layout = new javax.swing.GroupLayout(panelRound_11);
        panelRound_11.setLayout(panelRound_11Layout);
        panelRound_11Layout.setHorizontalGroup(
            panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(196, 196, 196))
            .addGroup(panelRound_11Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FieldPasswordMasyarakat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FieldIDMasyarakat, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                        .addComponent(FieldNamaMasyarakat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FieldUsernameMasyarakat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSimpanAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        panelRound_11Layout.setVerticalGroup(
            panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FieldIDMasyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(FieldNamaMasyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(FieldUsernameMasyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldPasswordMasyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(FieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonSimpanAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound_12Layout = new javax.swing.GroupLayout(panelRound_12);
        panelRound_12.setLayout(panelRound_12Layout);
        panelRound_12Layout.setHorizontalGroup(
            panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_12Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(panelRound_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
        );
        panelRound_12Layout.setVerticalGroup(
            panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_12Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(panelRound_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        getContentPane().add(panelRound_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 1120, 1070));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("<html>MEMBUAT AKUN MASYARAKAT</html>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldNamaMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNamaMasyarakatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNamaMasyarakatActionPerformed

    private void FieldNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNoTelpActionPerformed

    private void ButtonSimpanAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanAkunActionPerformed
      
            komponen();
            int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda Sudah Yakin?");
            
            if (konfirmasi == 0) {

                try {
                    String sql = "INSERT INTO tb_masyarakat values (?, ?, ?, ?, ?)";
                    this.pst = connect.connectDB().prepareStatement(sql);
                    this.pst.setString(1, InputidMasyarakat);
                    this.pst.setString(2, InputNamaMasyarakat);
                    this.pst.setString(3, InputUsernameMasyarakat);
                    this.pst.setString(4, InputPsswordMasyarakat);
                    this.pst.setString(5, InputNoMasyarakat);
                    this.pst.execute();

                    int input = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Menyimpannya?", "Silahkan Pilih ", JOptionPane.YES_NO_OPTION);
                    new FormUser().setVisible(true);
                    AutoNumberID();
                    
                } catch (Exception e) {
                    JOptionPane.showConfirmDialog(null, e);
                }
                }
            
    }//GEN-LAST:event_ButtonSimpanAkunActionPerformed

    private void FieldUsernameMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldUsernameMasyarakatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldUsernameMasyarakatActionPerformed

    private void FieldUsernameMasyarakatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldUsernameMasyarakatKeyReleased
        // TODO add your handling code here:
        komponen();
        try {
            String sql = "select username from tb_masyarakat where username=?";
            this.pst = connect.connectDB().prepareStatement(sql); 
            this.pst.setString(1, InputUsernameMasyarakat);
            this.rs = pst.executeQuery(); 
            if(rs.next()){
                FieldPasswordMasyarakat.setVisible(false);
                FieldNoTelp.setVisible(false);
                labelError.setVisible(true);
                labelError.setForeground(Color.RED);
                labelError.setText("Username " + InputUsernameMasyarakat + " telah digunakan");
                
                FieldPasswordMasyarakat.setEditable(false);
                FieldNoTelp.setEditable(false);
             
                
            }else if(InputUsernameMasyarakat.equals("")){
                labelError.setVisible(false);
               
               
            }else  if(rs.next() == false){
              FieldPasswordMasyarakat.setVisible(true);
              FieldNoTelp.setVisible(true);
              labelError.setVisible(true);
              FieldPasswordMasyarakat.setEditable(true);
                FieldNoTelp.setEditable(true);
              labelError.setText("Username " + InputUsernameMasyarakat + " dapat digunakan!");
              labelError.setForeground(Color.GREEN);
              
              
             
              
            }
            
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_FieldUsernameMasyarakatKeyReleased

    private void FieldIDMasyarakatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldIDMasyarakatKeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
          FieldNamaMasyarakat.requestFocus();
       }
    }//GEN-LAST:event_FieldIDMasyarakatKeyReleased

    private void FieldUsernameMasyarakatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldUsernameMasyarakatKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
          
          FieldPasswordMasyarakat.requestFocus();
       }
    }//GEN-LAST:event_FieldUsernameMasyarakatKeyPressed

    private void FieldPasswordMasyarakatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldPasswordMasyarakatKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
          FieldNoTelp.requestFocus();
       }
        
    }//GEN-LAST:event_FieldPasswordMasyarakatKeyPressed

    private void FieldNoTelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNoTelpKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            komponen();
            int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda Sudah Yakin?");
            
            if (konfirmasi == 0) {

                try {
                    String sql = "INSERT INTO tb_masyarakat values (?, ?, ?, ?, ?)";
                    this.pst = connect.connectDB().prepareStatement(sql);
                    this.pst.setString(1, InputidMasyarakat);
                    this.pst.setString(2, InputNamaMasyarakat);
                    this.pst.setString(3, InputUsernameMasyarakat);
                    this.pst.setString(4, InputPsswordMasyarakat);
                    this.pst.setString(5, InputNoMasyarakat);
                    this.pst.execute();

                    int input = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Menyimpannya?", "Silahkan Pilih ", JOptionPane.YES_NO_OPTION);
                    new FormUser().setVisible(true);
                    AutoNumberID();
                    
                } catch (Exception e) {
                    JOptionPane.showConfirmDialog(null, e);
                }
                }
            }
    }//GEN-LAST:event_FieldNoTelpKeyPressed

    private void FieldNamaMasyarakatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNamaMasyarakatKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            FieldUsernameMasyarakat.requestFocus();
        }
            
    }//GEN-LAST:event_FieldNamaMasyarakatKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MembuatAkunMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MembuatAkunMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MembuatAkunMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MembuatAkunMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MembuatAkunMasyarakat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button ButtonSimpanAkun;
    private textfield.TextField FieldIDMasyarakat;
    private textfield.TextField FieldNamaMasyarakat;
    private textfield.TextField FieldNoTelp;
    private textfield.TextField FieldPasswordMasyarakat;
    private textfield.TextField FieldUsernameMasyarakat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelError;
    private LoginPage.PanelRound_1 panelRound_11;
    private LoginPage.PanelRound_1 panelRound_12;
    // End of variables declaration//GEN-END:variables

    public void AutoNumberID(){
        try {
            String sql = "select max(id) as autoNumber from tb_masyarakat "; 
            this.pst = connect.connectDB().prepareStatement(sql); 
            this.rs = pst.executeQuery();
            if(rs.next()){
                int autoNumber = rs.getInt("autoNumber"); 
                FieldIDMasyarakat.setText(String.valueOf(autoNumber + 1));
            }
        } catch (Exception e) {
        }
    }
}
