/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormUntukLogin;

import connecction.connect;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ALYA
 */
public class NewPasswordMasyarakat extends javax.swing.JFrame {
    String inputUsername, inputPassword, inputConfirmUsername, inputConfirmPassword, inputID;
    
    PreparedStatement pst;
    ResultSet rs;
    

    /**
     * Creates new form NewPasswordMasyarakat
     */
    public NewPasswordMasyarakat() {
        initComponents();
        getContentPane().setBackground(Color.white);
        FieldGantiUsername.setVisible(false);
        FieldGantiPassword.setVisible(false);
        FieldConfirmPassword.setVisible(false);
        ButtonGantiAkun.setVisible(false);
        labelError.setVisible(false);
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
 
    }
    
    public void komponen(){
        
        inputID = fieldIDMasyarakat.getText().trim();

        inputUsername = FieldGantiUsername.getText().trim();
        inputPassword =  FieldGantiPassword.getText().trim();
        inputConfirmPassword = FieldConfirmPassword.getText().trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound_12 = new LoginPage.PanelRound_1();
        panelRound_11 = new LoginPage.PanelRound_1();
        FieldGantiUsername = new textfield.TextField();
        FieldGantiPassword = new textfield.TextField();
        ButtonGantiAkun = new button.Button();
        FieldConfirmPassword = new textfield.TextField();
        fieldIDMasyarakat = new textfield.TextField();
        ButtonGantiAkun1 = new button.Button();
        labelError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRound_13 = new LoginPage.PanelRound_1();
        panelRound_15 = new LoginPage.PanelRound_1();
        panelRound_16 = new LoginPage.PanelRound_1();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound_12.setBackground(new java.awt.Color(255, 255, 255));

        panelRound_11.setBackground(new java.awt.Color(38, 71, 136));
        panelRound_11.setRoundBottomLeft(50);
        panelRound_11.setRoundBottomRight(50);
        panelRound_11.setRoundTopLeft(50);
        panelRound_11.setRoundTopRight(50);

        FieldGantiUsername.setLabelText("Ganti Username ");
        FieldGantiUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldGantiUsernameActionPerformed(evt);
            }
        });
        FieldGantiUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldGantiUsernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldGantiUsernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FieldGantiUsernameKeyTyped(evt);
            }
        });

        FieldGantiPassword.setLabelText("Ganti Password");
        FieldGantiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldGantiPasswordActionPerformed(evt);
            }
        });
        FieldGantiPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldGantiPasswordKeyPressed(evt);
            }
        });

        ButtonGantiAkun.setBackground(new java.awt.Color(255, 1, 91));
        ButtonGantiAkun.setForeground(new java.awt.Color(255, 255, 255));
        ButtonGantiAkun.setText("Ganti Password");
        ButtonGantiAkun.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonGantiAkun.setShadowColor(new java.awt.Color(0, 0, 0));
        ButtonGantiAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGantiAkunActionPerformed(evt);
            }
        });

        FieldConfirmPassword.setLabelText("Konfirmasi Password");
        FieldConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldConfirmPasswordKeyPressed(evt);
            }
        });

        fieldIDMasyarakat.setLabelText("Masukan ID");
        fieldIDMasyarakat.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                fieldIDMasyarakatInputMethodTextChanged(evt);
            }
        });
        fieldIDMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIDMasyarakatActionPerformed(evt);
            }
        });
        fieldIDMasyarakat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldIDMasyarakatKeyPressed(evt);
            }
        });

        ButtonGantiAkun1.setBackground(new java.awt.Color(255, 1, 91));
        ButtonGantiAkun1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonGantiAkun1.setText("Cari ID");
        ButtonGantiAkun1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonGantiAkun1.setShadowColor(new java.awt.Color(0, 0, 0));
        ButtonGantiAkun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGantiAkun1ActionPerformed(evt);
            }
        });

        labelError.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        labelError.setForeground(new java.awt.Color(255, 255, 255));
        labelError.setText("message error");

        javax.swing.GroupLayout panelRound_11Layout = new javax.swing.GroupLayout(panelRound_11);
        panelRound_11.setLayout(panelRound_11Layout);
        panelRound_11Layout.setHorizontalGroup(
            panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_11Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonGantiAkun1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldIDMasyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FieldGantiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonGantiAkun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FieldGantiUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        panelRound_11Layout.setVerticalGroup(
            panelRound_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_11Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(fieldIDMasyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonGantiAkun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(FieldGantiUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelError)
                .addGap(36, 36, 36)
                .addComponent(FieldGantiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(FieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(ButtonGantiAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 140));
        jLabel2.setText("<html>GANTI USERNAME & PASSWORD</html>");

        panelRound_13.setBackground(new java.awt.Color(38, 71, 136));
        panelRound_13.setRoundBottomRight(50);
        panelRound_13.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound_13Layout = new javax.swing.GroupLayout(panelRound_13);
        panelRound_13.setLayout(panelRound_13Layout);
        panelRound_13Layout.setHorizontalGroup(
            panelRound_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panelRound_13Layout.setVerticalGroup(
            panelRound_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        panelRound_15.setBackground(new java.awt.Color(38, 71, 136));
        panelRound_15.setRoundBottomLeft(50);
        panelRound_15.setRoundTopLeft(50);

        javax.swing.GroupLayout panelRound_15Layout = new javax.swing.GroupLayout(panelRound_15);
        panelRound_15.setLayout(panelRound_15Layout);
        panelRound_15Layout.setHorizontalGroup(
            panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panelRound_15Layout.setVerticalGroup(
            panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        panelRound_16.setBackground(new java.awt.Color(38, 71, 136));
        panelRound_16.setRoundBottomLeft(20);
        panelRound_16.setRoundBottomRight(20);
        panelRound_16.setRoundTopLeft(20);
        panelRound_16.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound_16Layout = new javax.swing.GroupLayout(panelRound_16);
        panelRound_16.setLayout(panelRound_16Layout);
        panelRound_16Layout.setHorizontalGroup(
            panelRound_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );
        panelRound_16Layout.setVerticalGroup(
            panelRound_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(38, 71, 136));
        jLabel3.setText("MASYARAKAT");

        javax.swing.GroupLayout panelRound_12Layout = new javax.swing.GroupLayout(panelRound_12);
        panelRound_12.setLayout(panelRound_12Layout);
        panelRound_12Layout.setHorizontalGroup(
            panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_12Layout.createSequentialGroup()
                .addComponent(panelRound_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, Short.MAX_VALUE)
                .addComponent(panelRound_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(477, 477, 477)
                .addComponent(panelRound_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_12Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(810, 810, 810))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_12Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(744, 744, 744))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_12Layout.createSequentialGroup()
                        .addComponent(panelRound_16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(731, 731, 731))))
        );
        panelRound_12Layout.setVerticalGroup(
            panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_12Layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_12Layout.createSequentialGroup()
                        .addComponent(panelRound_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_12Layout.createSequentialGroup()
                        .addComponent(panelRound_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))))
            .addGroup(panelRound_12Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(panelRound_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelRound_16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelRound_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1810, 1040));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldGantiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldGantiPasswordActionPerformed
        komponen();
    }//GEN-LAST:event_FieldGantiPasswordActionPerformed

    private void fieldIDMasyarakatInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fieldIDMasyarakatInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIDMasyarakatInputMethodTextChanged

    private void FieldGantiUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldGantiUsernameActionPerformed
      
    }//GEN-LAST:event_FieldGantiUsernameActionPerformed

    private void FieldGantiUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldGantiUsernameKeyTyped
    
    }//GEN-LAST:event_FieldGantiUsernameKeyTyped

    private void ButtonGantiAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGantiAkunActionPerformed
        // TODO add your handling code here:
        komponen();
     
        if(inputUsername.equals(inputConfirmPassword)){
            try {
                String sql = "update tb_petugas set username=?, password=? where id_petugas=?";
                this.pst = connect.connectDB().prepareStatement(sql);
                this.pst.setString(1, inputUsername);
                this.pst.setString(2, inputPassword);
                this.pst.setString(3, inputID);
                this.pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil Diubah", "Pesan Dari Admin", JOptionPane.INFORMATION_MESSAGE);
                new FormUser().setVisible(true);
            } catch (Exception e) {
            }
        }else if(!inputPassword.equals(inputConfirmPassword)){
            JOptionPane.showMessageDialog(null, "Password Tidak sama");
        }

    }//GEN-LAST:event_ButtonGantiAkunActionPerformed

    private void ButtonGantiAkun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGantiAkun1ActionPerformed
        // TODO add your handling code here:
        komponen();
        try {

            //            String sql = "select * from tb_petugas join tb_level ON tb_petugas.id_petugas=? using(id_level) where tb_level.level='Petugas'";
            String sql = "select id from tb_masyarakat where id=?";
            this.pst = connect.connectDB().prepareStatement(sql);
            this.pst.setString(1, inputID);
            this.rs = pst.executeQuery();

            if(rs.next()){
                FieldGantiUsername.setVisible(true);
                FieldGantiPassword.setVisible(true);
             
                FieldConfirmPassword.setVisible(true);
                ButtonGantiAkun.setVisible(true);

            }else{
                JOptionPane.showMessageDialog(null, "ID " + inputID + " Tidak ditemukan", "Pesan dari Admin", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ButtonGantiAkun1ActionPerformed

    private void fieldIDMasyarakatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldIDMasyarakatKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
              komponen();
        try {

            //            String sql = "select * from tb_petugas join tb_level ON tb_petugas.id_petugas=? using(id_level) where tb_level.level='Petugas'";
            String sql = "select id from tb_masyarakat where id=?";
            this.pst = connect.connectDB().prepareStatement(sql);
            this.pst.setString(1, inputID);
            this.rs = pst.executeQuery();

            if(rs.next()){
                FieldGantiUsername.setVisible(true);
                FieldGantiPassword.setVisible(true);
             
                FieldConfirmPassword.setVisible(true);
                ButtonGantiAkun.setVisible(true);
                
                FieldGantiPassword.setEditable(false);
                FieldConfirmPassword.setEditable(false);
                
                FieldGantiUsername.requestFocus();

            }else{
                JOptionPane.showMessageDialog(null, "ID " + inputID + " Tidak ditemukan", "Pesan dari Admin", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
        }
       }
    }//GEN-LAST:event_fieldIDMasyarakatKeyPressed

    private void fieldIDMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIDMasyarakatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIDMasyarakatActionPerformed

    private void FieldGantiUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldGantiUsernameKeyReleased
        komponen();
        try {
            String sql = "select username from tb_masyarakat where username=?";
            this.pst = connect.connectDB().prepareStatement(sql); 
            this.pst.setString(1, inputUsername);
            this.rs = pst.executeQuery(); 
            if(rs.next()){
                labelError.setVisible(true);
                labelError.setForeground(Color.RED);
                labelError.setText("Username " + inputUsername + " telah digunakan");
             
                
            }else if(inputUsername.equals("")){
                labelError.setVisible(false);
               
               
            }else  if(rs.next() == false){
              labelError.setVisible(true);
              labelError.setText("Username " + inputUsername + " dapat digunakan!");
              labelError.setForeground(Color.GREEN);
              
              FieldGantiPassword.setEditable(true); 
              FieldConfirmPassword.setEditable(true);
              
              
            }
            
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_FieldGantiUsernameKeyReleased

    private void FieldGantiUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldGantiUsernameKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER){
          FieldGantiPassword.requestFocus();
       }
    }//GEN-LAST:event_FieldGantiUsernameKeyPressed

    private void FieldGantiPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldGantiPasswordKeyPressed
         if(evt.getKeyCode()== KeyEvent.VK_ENTER){
          FieldConfirmPassword.requestFocus();
       }
    }//GEN-LAST:event_FieldGantiPasswordKeyPressed

    private void FieldConfirmPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldConfirmPasswordKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
           komponen();
     
        if(inputPassword.equals(inputConfirmPassword)){
            try {
                String sql = "update tb_masyarakat set username=?, password=? where id=?";
                this.pst = connect.connectDB().prepareStatement(sql);
                this.pst.setString(1, inputUsername);
                this.pst.setString(2, inputPassword);
                this.pst.setString(3, inputID);
                this.pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil Diubah", "Pesan Dari Admin", JOptionPane.INFORMATION_MESSAGE);
                new FormUser().setVisible(true);
            } catch (Exception e) {
            }
        }else if(!inputPassword.equals(inputConfirmPassword)){
            JOptionPane.showMessageDialog(null, "Password Tidak sama");
        }
       }
    }//GEN-LAST:event_FieldConfirmPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPasswordMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPasswordMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPasswordMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPasswordMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPasswordMasyarakat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button ButtonGantiAkun;
    private button.Button ButtonGantiAkun1;
    private textfield.TextField FieldConfirmPassword;
    private textfield.TextField FieldGantiPassword;
    private textfield.TextField FieldGantiUsername;
    private textfield.TextField fieldIDMasyarakat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelError;
    private LoginPage.PanelRound_1 panelRound_11;
    private LoginPage.PanelRound_1 panelRound_12;
    private LoginPage.PanelRound_1 panelRound_13;
    private LoginPage.PanelRound_1 panelRound_14;
    private LoginPage.PanelRound_1 panelRound_15;
    private LoginPage.PanelRound_1 panelRound_16;
    // End of variables declaration//GEN-END:variables
}
