/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Page;

import FormUntukLogin.FormUser;
import connecction.connect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import table.TableCustom;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALYA
 */
public class PageUser extends javax.swing.JFrame {
     DefaultTableModel tabmode;
     String IDTawar, IDBarang, IDUser, HargaAwal, HargaAkhir;
     Connection conn;
    PreparedStatement pst;
    ResultSet set; 
     ResultSet SearchBarang=null;
     connect konek = new connect();

    /**
     * Creates new form PageUser
     */
    public PageUser() {
        initComponents();
        autoNumberPenawaran();
        idBarang();
        idUser();
        showData();
        showDataBarang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelRound_11 = new LoginPage.PanelRound_1();
        panelRound_12 = new LoginPage.PanelRound_1();
        ButtonStuff = new button.Button();
        ButtonPrice = new button.Button();
        panelRound_13 = new LoginPage.PanelRound_1();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        button5 = new button.Button();
        button6 = new button.Button();
        button7 = new button.Button();
        ButtonLogOut = new button.Button();
        PageOne = new javax.swing.JTabbedPane();
        FrameDataPenawaran = new javax.swing.JPanel();
        panelRound_15 = new LoginPage.PanelRound_1();
        FieldTawar = new textfield.TextField_1();
        FieldHL = new textfield.TextField_1();
        FieldNB = new textfield.TextField_1();
        CbUser = new combobox.Combobox();
        FieldNU = new textfield.TextField_1();
        ButtonSave = new button.Button();
        ScrollPanePenawaran = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        ButtonEdit = new button.Button();
        ButtonDelete = new button.Button();
        ButtonClear = new button.Button();
        FieldHB = new textfield.TextField_1();
        CbBarang = new combobox.Combobox();
        button15 = new button.Button();
        FieldCariDataMasyarakat = new textfield.TextField_1();
        jLabel3 = new javax.swing.JLabel();
        FrameDataBarang = new javax.swing.JPanel();
        panelRound_14 = new LoginPage.PanelRound_1();
        ScrollPaneBarang = new javax.swing.JScrollPane();
        TableBarangUser = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1081, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelRound_11.setBackground(new java.awt.Color(255, 255, 255));
        panelRound_11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound_12.setBackground(new java.awt.Color(255, 223, 129));
        panelRound_12.setRoundBottomRight(30);
        panelRound_12.setRoundTopRight(30);

        ButtonStuff.setBackground(new java.awt.Color(126, 203, 87));
        ButtonStuff.setForeground(new java.awt.Color(255, 255, 255));
        ButtonStuff.setText("<html>DAFTAR BARANG</html>");
        ButtonStuff.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonStuff.setRound(20);
        ButtonStuff.setShadowColor(new java.awt.Color(0, 204, 0));
        ButtonStuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStuffActionPerformed(evt);
            }
        });

        ButtonPrice.setBackground(new java.awt.Color(126, 203, 87));
        ButtonPrice.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPrice.setText("<html>PENGAJUAN HARGA</html>");
        ButtonPrice.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonPrice.setRound(20);
        ButtonPrice.setShadowColor(new java.awt.Color(0, 204, 0));
        ButtonPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPriceActionPerformed(evt);
            }
        });

        panelRound_13.setBackground(new java.awt.Color(126, 203, 87));
        panelRound_13.setRoundBottomLeft(30);
        panelRound_13.setRoundBottomRight(30);
        panelRound_13.setRoundTopLeft(30);
        panelRound_13.setRoundTopRight(200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginPage/man (1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>HALAMAN MASYARAKAT</html>");

        javax.swing.GroupLayout panelRound_13Layout = new javax.swing.GroupLayout(panelRound_13);
        panelRound_13.setLayout(panelRound_13Layout);
        panelRound_13Layout.setHorizontalGroup(
            panelRound_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
        );
        panelRound_13Layout.setVerticalGroup(
            panelRound_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_13Layout.createSequentialGroup()
                .addGroup(panelRound_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound_13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(panelRound_13Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        button5.setBackground(new java.awt.Color(126, 203, 87));
        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/shopping-cart.png"))); // NOI18N
        button5.setRound(20);
        button5.setShadowColor(new java.awt.Color(0, 204, 0));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(126, 203, 87));
        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/circle-heart.png"))); // NOI18N
        button6.setRound(20);
        button6.setShadowColor(new java.awt.Color(0, 204, 0));

        button7.setBackground(new java.awt.Color(126, 203, 87));
        button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/logout.png"))); // NOI18N
        button7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        button7.setShadowColor(new java.awt.Color(0, 204, 0));

        ButtonLogOut.setBackground(new java.awt.Color(126, 203, 87));
        ButtonLogOut.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogOut.setText("<html>KELUAR</html>");
        ButtonLogOut.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonLogOut.setShadowColor(new java.awt.Color(0, 204, 0));
        ButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound_12Layout = new javax.swing.GroupLayout(panelRound_12);
        panelRound_12.setLayout(panelRound_12Layout);
        panelRound_12Layout.setHorizontalGroup(
            panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound_12Layout.createSequentialGroup()
                        .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonStuff, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ButtonPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ButtonLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound_12Layout.setVerticalGroup(
            panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_12Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(panelRound_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonStuff)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        panelRound_11.add(panelRound_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 360, 920));

        FrameDataPenawaran.setBackground(new java.awt.Color(255, 255, 255));

        panelRound_15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound_15.setRoundBottomLeft(70);
        panelRound_15.setRoundBottomRight(70);
        panelRound_15.setRoundTopLeft(70);
        panelRound_15.setRoundTopRight(70);

        FieldTawar.setLabelText("ID PENAWARAN");
        FieldTawar.setLineColor(new java.awt.Color(126, 203, 87));

        FieldHL.setLabelText("HARGA LELANG");
        FieldHL.setLineColor(new java.awt.Color(126, 203, 87));

        FieldNB.setLabelText("NAMA BARANG");
        FieldNB.setLineColor(new java.awt.Color(126, 203, 87));

        CbUser.setLineColor(new java.awt.Color(126, 203, 87));
        CbUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbUserActionPerformed(evt);
            }
        });

        FieldNU.setLabelText("NAMA ANDA");
        FieldNU.setLineColor(new java.awt.Color(126, 203, 87));

        ButtonSave.setBackground(new java.awt.Color(126, 203, 87));
        ButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/clipboard (1).png"))); // NOI18N
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "HARGA TAWAR", "ID BARANG", "ID USER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserMouseClicked(evt);
            }
        });
        ScrollPanePenawaran.setViewportView(tableUser);
        if (tableUser.getColumnModel().getColumnCount() > 0) {
            tableUser.getColumnModel().getColumn(0).setPreferredWidth(60);
            tableUser.getColumnModel().getColumn(1).setPreferredWidth(190);
            tableUser.getColumnModel().getColumn(2).setPreferredWidth(250);
            tableUser.getColumnModel().getColumn(3).setPreferredWidth(250);
        }

        ButtonEdit.setBackground(new java.awt.Color(126, 203, 87));
        ButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/edit.png"))); // NOI18N
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonDelete.setBackground(new java.awt.Color(126, 203, 87));
        ButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/trash-bin.png"))); // NOI18N
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonClear.setBackground(new java.awt.Color(126, 203, 87));
        ButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/clean.png"))); // NOI18N
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });

        FieldHB.setLabelText("HARGA AWAL");
        FieldHB.setLineColor(new java.awt.Color(126, 203, 87));

        CbBarang.setLineColor(new java.awt.Color(126, 203, 87));
        CbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbBarangActionPerformed(evt);
            }
        });

        button15.setBackground(new java.awt.Color(126, 203, 87));
        button15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/search (1).png"))); // NOI18N
        button15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button15MouseClicked(evt);
            }
        });
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });

        FieldCariDataMasyarakat.setLabelText("SILAHKAN CARI");
        FieldCariDataMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCariDataMasyarakatActionPerformed(evt);
            }
        });
        FieldCariDataMasyarakat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldCariDataMasyarakatKeyReleased(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(126, 203, 87));
        jLabel3.setText("<html>PENGAJUAN HARGA MASYARAKAT.</html>");

        javax.swing.GroupLayout panelRound_15Layout = new javax.swing.GroupLayout(panelRound_15);
        panelRound_15.setLayout(panelRound_15Layout);
        panelRound_15Layout.setHorizontalGroup(
            panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_15Layout.createSequentialGroup()
                .addGroup(panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound_15Layout.createSequentialGroup()
                        .addGroup(panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRound_15Layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(ButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelRound_15Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CbUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                                    .addComponent(FieldHL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FieldTawar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FieldNU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FieldHB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FieldNB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CbBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_15Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255)))
                .addGroup(panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_15Layout.createSequentialGroup()
                        .addGroup(panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound_15Layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ScrollPanePenawaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_15Layout.createSequentialGroup()
                        .addComponent(FieldCariDataMasyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(button15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );
        panelRound_15Layout.setVerticalGroup(
            panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldCariDataMasyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_15Layout.createSequentialGroup()
                        .addComponent(FieldTawar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(CbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(FieldNB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(FieldHB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(FieldHL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(CbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(FieldNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_15Layout.createSequentialGroup()
                        .addComponent(ScrollPanePenawaran, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRound_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75))))
        );

        javax.swing.GroupLayout FrameDataPenawaranLayout = new javax.swing.GroupLayout(FrameDataPenawaran);
        FrameDataPenawaran.setLayout(FrameDataPenawaranLayout);
        FrameDataPenawaranLayout.setHorizontalGroup(
            FrameDataPenawaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameDataPenawaranLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panelRound_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(541, Short.MAX_VALUE))
        );
        FrameDataPenawaranLayout.setVerticalGroup(
            FrameDataPenawaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameDataPenawaranLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(panelRound_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        PageOne.addTab("tab1", FrameDataPenawaran);

        FrameDataBarang.setBackground(new java.awt.Color(255, 255, 255));

        panelRound_14.setBackground(new java.awt.Color(255, 223, 129));
        panelRound_14.setRoundBottomLeft(50);
        panelRound_14.setRoundBottomRight(50);
        panelRound_14.setRoundTopLeft(50);
        panelRound_14.setRoundTopRight(50);

        TableBarangUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAMA BARANG", "TANGGAL", "HARGA", "DESKRIPSI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPaneBarang.setViewportView(TableBarangUser);
        if (TableBarangUser.getColumnModel().getColumnCount() > 0) {
            TableBarangUser.getColumnModel().getColumn(0).setPreferredWidth(180);
            TableBarangUser.getColumnModel().getColumn(1).setPreferredWidth(90);
            TableBarangUser.getColumnModel().getColumn(2).setPreferredWidth(90);
            TableBarangUser.getColumnModel().getColumn(3).setPreferredWidth(250);
        }

        javax.swing.GroupLayout panelRound_14Layout = new javax.swing.GroupLayout(panelRound_14);
        panelRound_14.setLayout(panelRound_14Layout);
        panelRound_14Layout.setHorizontalGroup(
            panelRound_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound_14Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(ScrollPaneBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 1408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelRound_14Layout.setVerticalGroup(
            panelRound_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound_14Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(ScrollPaneBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout FrameDataBarangLayout = new javax.swing.GroupLayout(FrameDataBarang);
        FrameDataBarang.setLayout(FrameDataBarangLayout);
        FrameDataBarangLayout.setHorizontalGroup(
            FrameDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameDataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
        );
        FrameDataBarangLayout.setVerticalGroup(
            FrameDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameDataBarangLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(panelRound_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        PageOne.addTab("tab2", FrameDataBarang);

        panelRound_11.add(PageOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, -30, -1, 1070));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound_11, javax.swing.GroupLayout.DEFAULT_SIZE, 1921, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void ButtonStuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStuffActionPerformed
        // TODO add your handling code here:
        PageOne.setSelectedIndex(1);
    }//GEN-LAST:event_ButtonStuffActionPerformed

    private void ButtonPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPriceActionPerformed
        // TODO add your handling code here:
        PageOne.setSelectedIndex(0);
    }//GEN-LAST:event_ButtonPriceActionPerformed

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
        // TODO add your handling code here:
        try{
            IDBarang =  (String)  CbBarang.getSelectedItem();
            IDUser = (String)CbUser.getSelectedItem();
            IDTawar = FieldTawar.getText();
            HargaAkhir = FieldHL.getText();

            Connection con = connect.connectDB();
            Statement st = con.createStatement();
            String sql = "insert into penawaran values ('"+ IDTawar+
            "','"+HargaAkhir+
            "','"+IDBarang+
            "','"+IDUser+"')";
            st.execute(sql);
            showData();
            autoNumberPenawaran();

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ButtonSaveActionPerformed

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void ButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        new FormUser().setVisible(true);
    }//GEN-LAST:event_ButtonLogOutActionPerformed

    private void CbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbBarangActionPerformed
        // TODO add your handling code here:
        try{
            String Click = CbBarang.getSelectedItem().toString();
            java.sql.Connection conn = (java.sql.Connection)connect.connectDB();
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet sql = st.executeQuery("select * from tb_barang where id_barang = '"+Click+"'");

            if(sql.next()){
                String add1 = sql.getString("nama_barang");
                FieldNB.setText(add1);
                String add2 = sql.getString("harga_awal");
                FieldHB.setText(add2);

            }
        } catch (Exception e){

        }
    }//GEN-LAST:event_CbBarangActionPerformed

    private void CbUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbUserActionPerformed
        // TODO add your handling code here:
        try{
            String Click = CbUser.getSelectedItem().toString();
            java.sql.Connection conn = (java.sql.Connection)connect.connectDB();
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet sql = st.executeQuery("select * from tb_masyarakat where id = '"+Click+"'");

            if(sql.next()){
                String add1 = sql.getString("nama");
                FieldNU.setText(add1);
                

            }
        } catch (Exception e){

        }
    }//GEN-LAST:event_CbUserActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
        
       try{
            IDBarang =  (String)  CbBarang.getSelectedItem();
            IDUser = (String)CbUser.getSelectedItem();
            IDTawar = FieldTawar.getText();
            HargaAkhir = FieldHL.getText();
            
            String sql = "update penawaran set harga_tawar='"+HargaAkhir+ 
                    "' where id_penawaran='"+IDTawar+"'";

            java.sql.Connection conn =(java.sql.Connection)connect.connectDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            int input = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Mengeditnya?", "Silahkan Pilih ", JOptionPane.YES_OPTION);
            showData();

        } catch (Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void tableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserMouseClicked
        // TODO add your handling code here:
        mouseClickPaket();
    }//GEN-LAST:event_tableUserMouseClicked

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        // TODO add your handling code here:
        try{
            
            IDTawar = FieldTawar.getText();

            java.sql.Connection conn = (java.sql.Connection)connect.connectDB();
            String sql = "delete from penawaran where id_penawaran ='"+IDTawar+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            int input = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Menghapusnya?", "Silahkan Pilih ", JOptionPane.YES_NO_OPTION);
        } catch (Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
        showData();
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void FieldCariDataMasyarakatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldCariDataMasyarakatKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FieldCariDataMasyarakatKeyReleased

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
        SearchDataPenawaran();
    }//GEN-LAST:event_button15ActionPerformed

    private void FieldCariDataMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCariDataMasyarakatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCariDataMasyarakatActionPerformed

    private void button15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MouseClicked
        // TODO add your handling code here:
        SearchDataPenawaran();
    }//GEN-LAST:event_button15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button ButtonClear;
    private button.Button ButtonDelete;
    private button.Button ButtonEdit;
    private button.Button ButtonLogOut;
    private button.Button ButtonPrice;
    private button.Button ButtonSave;
    private button.Button ButtonStuff;
    private combobox.Combobox CbBarang;
    private combobox.Combobox CbUser;
    private textfield.TextField_1 FieldCariDataMasyarakat;
    private textfield.TextField_1 FieldHB;
    private textfield.TextField_1 FieldHL;
    private textfield.TextField_1 FieldNB;
    private textfield.TextField_1 FieldNU;
    private textfield.TextField_1 FieldTawar;
    private javax.swing.JPanel FrameDataBarang;
    private javax.swing.JPanel FrameDataPenawaran;
    private javax.swing.JTabbedPane PageOne;
    private javax.swing.JScrollPane ScrollPaneBarang;
    private javax.swing.JScrollPane ScrollPanePenawaran;
    private javax.swing.JTable TableBarangUser;
    private button.Button button15;
    private button.Button button5;
    private button.Button button6;
    private button.Button button7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private LoginPage.PanelRound_1 panelRound_11;
    private LoginPage.PanelRound_1 panelRound_12;
    private LoginPage.PanelRound_1 panelRound_13;
    private LoginPage.PanelRound_1 panelRound_14;
    private LoginPage.PanelRound_1 panelRound_15;
    private javax.swing.JTable tableUser;
    // End of variables declaration//GEN-END:variables


    public void idBarang(){
        try{
            java.sql.Connection conn = (java.sql.Connection)connect.connectDB();
            java.sql.Statement stat = conn.createStatement();
            String sql = "SELECT id_barang FROM tb_barang";
            java.sql.ResultSet set = stat.executeQuery(sql);
            while(set.next()){
                String idBarang = set.getString("id_barang");
                CbBarang.addItem(idBarang);
            }
        }catch (Exception e){
            
        }
            
    }
    
    public void idUser(){
        try{
            java.sql.Connection conn = (java.sql.Connection)connect.connectDB();
            java.sql.Statement stat = conn.createStatement();
            String sql = "SELECT id FROM tb_masyarakat";
            java.sql.ResultSet set = stat.executeQuery(sql);
            while(set.next()){
                String idUser = set.getString("id");
                CbUser.addItem(idUser);
            }
        }catch (Exception e){
            
        }
            
    }
    
    public void showData (){
        
        TableCustom.apply(ScrollPanePenawaran, TableCustom.TableType.MULTI_LINE);
        Object[] barang= {"ID", "HARGA TAWAR", "ID BARANG",  "ID USER"};
        tabmode = new DefaultTableModel(null, barang);
        tableUser.setModel(tabmode);
        
        try{
            java.sql.Connection conn = (java.sql.Connection)connecction.connect.connectDB();
            String sql = "select * from penawaran";
            java.sql.Statement stat = conn.createStatement();
            ResultSet set = stat.executeQuery(sql);
            
            while(set.next()){
                String[] data = {
                    set.getString("id_penawaran"),
                    set.getString("harga_tawar"),
                    set.getString("id_barang"),
                    set.getString("id")
                   
                };
                tabmode.addRow(data);
                }
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            
        }
    }
    
    
    public void showDataBarang (){
        TableCustom.apply(ScrollPaneBarang, TableCustom.TableType.MULTI_LINE);
        Object[] barang= {"ID","NAMA BARANG", "TANGGAL",  "HARGA AWAL", "DESKRIPSI"};
        tabmode = new DefaultTableModel(null, barang);
        TableBarangUser.setModel(tabmode);
        
        try{
            java.sql.Connection conn = (java.sql.Connection)connecction.connect.connectDB();
            String sql = "select * from tb_barang";
            java.sql.Statement stat = conn.createStatement();
            ResultSet set = stat.executeQuery(sql);
            
            while(set.next()){
                String[] data = {
                    set.getString("id_barang"),
                    set.getString("nama_barang"),
                    set.getString("tanggal"),
                    set.getString("harga_awal"),
                    set.getString("desc_barang")
                };
                tabmode.addRow(data);
                }
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            
        }
    }
    
    public void clear(){
        FieldTawar.setText("");
        CbBarang.setSelectedItem("-");
        FieldNB.setText("");
        FieldHB.setText("");
        FieldHL.setText("");
        CbUser.setSelectedItem("-");
        FieldNU.setText("");
        
        
    }
    
    public void delete(){
        int row= tabmode.getRowCount();
        for( int i=0; i<row; i++){
            tabmode.removeRow(0);
        }
    }
    
    
    public void mouseClickPaket () {
int baris = tableUser.getSelectedRow () ;
String idP = tableUser.getModel (). getValueAt (baris, 0). toString () ;
String hP = tableUser.getModel () .getValueAt (baris, 1) .toString ();
String idB = tableUser.getModel (). getValueAt (baris, 2). toString () ;
String idU = tableUser.getModel().getValueAt(baris, 3).toString();


FieldTawar.setText(idP);
FieldHL.setText(hP);
CbBarang.setSelectedItem(idB);
CbUser.setSelectedItem(idU);


    
    }
    
    private void SearchDataPenawaran(){
        
         tableUser.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            TableCustom.apply(ScrollPanePenawaran, TableCustom.TableType.MULTI_LINE);
            Object[] search = {"ID PENAWARAN","ID BARANG","ID MASYARAKAT", "HARGA TAWAR"};
            tabmode= new DefaultTableModel(null, search);
            tableUser.setModel(tabmode);
            
            String cari = FieldCariDataMasyarakat.getText();
        try{
            String sql = "SELECT * from penawaran WHERE id_penawaran like? or id_barang like? or id like? or harga_tawar like?"; 
            this.pst = connect.connectDB().prepareStatement(sql); 
            this.pst.setString(1, "%" + cari + "%");
            this.pst.setString(2, "%" + cari + "%");
            this.pst.setString(3, "%" + cari + "%");
            this.pst.setString(4, "%" + cari + "%");
            
            this.set = pst.executeQuery(); 
           
       
            while(set.next()){
                Object[] data={
                    
                    set.getString("id_penawaran"),
                    set.getString("id_barang"),
                    set.getString("id"),
                    set.getString("harga_tawar")
                };
                tabmode.addRow(data);
                }
        } catch (Exception e){
        }
    }
    
    public void autoNumberPenawaran(){
        try {
            String sql = "select max(id_penawaran) as autoNumber from penawaran "; 
            this.pst = connect.connectDB().prepareStatement(sql); 
            this.set = pst.executeQuery();
            if(set.next()){
                int autoNumber = set.getInt("autoNumber"); 
                FieldTawar.setText(String.valueOf(autoNumber + 1));
            }
        } catch (Exception e) {
        }
    }


}
